name: 'Run gradle task'
description: 'Run Android Gradle tasks'

branding:
  color: green
  icon: play

inputs:
  script:
    description: 'The ./gradlew command arguments'
    required: true
  android-licence:
    description: 'Your Android license agreement id'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.android-licence }}
    - ${{ inputs.script }}
